### ISSUE TITLE
Create project basic structure

### ISSUE THREAD

**Issue by ldmi3i** [rog-golang-buddies/api-hub_data-scraping-service#3]
Create basic interfaces and infrastructure.
Data scraping service supposed to 
1. Receive url string from the Queue.
2. Recognise the url type (currently url needs to be a link to swagger file, if not - error)
3. Check file availability and Download file (if not available - error).
4. Pass the file to the swagger parser.

The parser is supposed to check and parse file content and return API Definition (API Definition in this task it can be just empty struct).

Queue event listener will be created later. 
This task we can just suppose that queue event listener will retrieve some UrlRequest with url as one of the fields.
After that EventListener calls UrlEventHandler.handle(req UrlRequest) (ApiDefinition, error) method. (for instance)
So here you need to create logic starting from UrlEventHandler to Parser (Parser here just an interface with 'parse' method) .

**Comment by lucianolacurcia** [comment]
I think we have 3 clear components, the queue client, the scraper and the parser, maybe the last two could be on the same package.

**Comment by ldmi3i** [comment]
Yes, agree. Perhaps we also need some resolver component between scraper and parser. To recognise file type and choose correct parser. (or this logic may be inside the parser)
I found out that swagger could also have json format. So we need to support two parser implementations (.yml and .json) from the beginning.

**Comment by ldmi3i** [comment]
I've created very very veryyy rough draft just to express an idea of actions I'm thinking of (the packages turned out a little differently).
You may look through process/processor.go file where I added main processing steps to get an idea of functionality.
https://github.com/rog-golang-buddies/api-hub_data-scraping-service/pull/6/files

If we'll take something like this draft as a base. It needs next improvements:

1. Pass dependencies through constructor (here are places where objects create in the constructor but it's not it responsibility + it's not testable)
2. Check the context (processor (in PR) supposed to be launched as goroutine from event listener.
3. Packages. 'model' looks like not very representative package name.
4. Tests
5. Method description.
