### ISSUE TITLE
Implement Parser interface for the swagger YAML file.

### ISSUE THREAD

**Issue by ldmi3i** [rog-golang-buddies/api-hub_data-scraping-service#5]
Should be started after creation of interfaces and API definition model.
i.e. to #3 and #4 

You need to implement next logic:
1. Check that the file is swagger YAML file (maybe check version or some simple check)
2. Parse content into API Definition.

I looks to me that method should have signature like this:
parse(content []byte) (*model.ApiSpecDoc, error)

**Comment by pallasite99** [comment]
This can be used imo - [go-swagger](https://github.com/go-swagger/go-swagger)

But this is a tool ig and would not be our own implementation, so better to explore other avenues first

**Comment by pallasite99** [comment]
related link: https://stackoverflow.com/questions/49442799/validate-yaml-schema-with-golang-semantic-check

**Comment by ldmi3i** [comment]
Looks very interesting cause swagger is a complex format and convert it to ApiSpecDoc will be very "fun" task) And it would be great to find some tools to simplify this.
I think we need some reading tool to 'walk through' file tree structure in cycles (or recursion) and transform it.
But it looks like this swagger library contains only different code/swagger generation tools (and server). 
Correct me if I'm wrong please, I just took a brief look to the documentation and can miss something.

Probably we can use some parts of this tool to validate and read swagger file.

**Comment by pallasite99** [comment]
Yes @ldmi3i I think you maybe correct. 
The description mentioned that it can be used to both serialise and deserialise swagger files. For our use case, it might be used for say authentication and validation purpose but we should ideally try to do a barebones implementation of the other part ourselves

**Comment by ldmi3i** [comment]
@pallasite99 I missed something at first) This lib is great, it contains additional simple libs inside with different helpers.
Separate model https://github.com/go-openapi/spec
And document loader https://github.com/go-openapi/loads (based on spec).
It may save a lot of time for us. Instead of implementing 2 parsers for json and yaml manually we may just load them into this model and write one convert method.
Loader test file looks like good example https://github.com/go-openapi/loads/blob/master/loads_test/spec_circular_test.go

**Comment by pallasite99** [comment]
Yup, on second thoughts since this part is pretty common no need to reinvent the wheel for these purposes 👍

**Comment by haani-niyaz** [comment]
An alternate option to consider for validation and parsing:
https://github.com/getkin/kin-openapi
